theme: jekyll-theme-minimal
title: Samuel Matioli
description: Data & AI Architect
show_downloads: false
# logo: /assets/img/logo.png  # Uncomment and add your profile picture
google_analytics: # Optional - add your Google Analytics ID here 