
version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4
    platform: linux/amd64
    command: jekyll serve --watch --force_polling --host 0.0.0.0
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
